// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package security
type AlertClassification int

const (
    UNKNOWN_ALERTCLASSIFICATION AlertClassification = iota
    FALSEPOSITIVE_ALERTCLASSIFICATION
    TRUEPOSITIVE_ALERTCLASSIFICATION
    INFORMATIONALEXPECTEDACTIVITY_ALERTCLASSIFICATION
    UNKNOWNFUTUREVALUE_ALERTCLASSIFICATION
)

func (i AlertClassification) String() string {
    return []string{"unknown", "falsePositive", "truePositive", "informationalExpectedActivity", "unknownFutureValue"}[i]
}
func ParseAlertClassification(v string) (any, error) {
    result := UNKNOWN_ALERTCLASSIFICATION
    switch v {
        case "unknown":
            result = UNKNOWN_ALERTCLASSIFICATION
        case "falsePositive":
            result = FALSEPOSITIVE_ALERTCLASSIFICATION
        case "truePositive":
            result = TRUEPOSITIVE_ALERTCLASSIFICATION
        case "informationalExpectedActivity":
            result = INFORMATIONALEXPECTEDACTIVITY_ALERTCLASSIFICATION
        case "unknownFutureValue":
            result = UNKNOWNFUTUREVALUE_ALERTCLASSIFICATION
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeAlertClassification(values []AlertClassification) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i AlertClassification) isMultiValue() bool {
    return false
}
