// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package security
type DeviceHealthStatus int

const (
    ACTIVE_DEVICEHEALTHSTATUS DeviceHealthStatus = iota
    INACTIVE_DEVICEHEALTHSTATUS
    IMPAIREDCOMMUNICATION_DEVICEHEALTHSTATUS
    NOSENSORDATA_DEVICEHEALTHSTATUS
    NOSENSORDATAIMPAIREDCOMMUNICATION_DEVICEHEALTHSTATUS
    UNKNOWN_DEVICEHEALTHSTATUS
    UNKNOWNFUTUREVALUE_DEVICEHEALTHSTATUS
)

func (i DeviceHealthStatus) String() string {
    return []string{"active", "inactive", "impairedCommunication", "noSensorData", "noSensorDataImpairedCommunication", "unknown", "unknownFutureValue"}[i]
}
func ParseDeviceHealthStatus(v string) (any, error) {
    result := ACTIVE_DEVICEHEALTHSTATUS
    switch v {
        case "active":
            result = ACTIVE_DEVICEHEALTHSTATUS
        case "inactive":
            result = INACTIVE_DEVICEHEALTHSTATUS
        case "impairedCommunication":
            result = IMPAIREDCOMMUNICATION_DEVICEHEALTHSTATUS
        case "noSensorData":
            result = NOSENSORDATA_DEVICEHEALTHSTATUS
        case "noSensorDataImpairedCommunication":
            result = NOSENSORDATAIMPAIREDCOMMUNICATION_DEVICEHEALTHSTATUS
        case "unknown":
            result = UNKNOWN_DEVICEHEALTHSTATUS
        case "unknownFutureValue":
            result = UNKNOWNFUTUREVALUE_DEVICEHEALTHSTATUS
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeDeviceHealthStatus(values []DeviceHealthStatus) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i DeviceHealthStatus) isMultiValue() bool {
    return false
}
