// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package security
type HealthIssueStatus int

const (
    OPEN_HEALTHISSUESTATUS HealthIssueStatus = iota
    CLOSED_HEALTHISSUESTATUS
    SUPPRESSED_HEALTHISSUESTATUS
    UNKNOWNFUTUREVALUE_HEALTHISSUESTATUS
)

func (i HealthIssueStatus) String() string {
    return []string{"open", "closed", "suppressed", "unknownFutureValue"}[i]
}
func ParseHealthIssueStatus(v string) (any, error) {
    result := OPEN_HEALTHISSUESTATUS
    switch v {
        case "open":
            result = OPEN_HEALTHISSUESTATUS
        case "closed":
            result = CLOSED_HEALTHISSUESTATUS
        case "suppressed":
            result = SUPPRESSED_HEALTHISSUESTATUS
        case "unknownFutureValue":
            result = UNKNOWNFUTUREVALUE_HEALTHISSUESTATUS
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeHealthIssueStatus(values []HealthIssueStatus) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i HealthIssueStatus) isMultiValue() bool {
    return false
}
