// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package security
type RetentionTrigger int

const (
    DATELABELED_RETENTIONTRIGGER RetentionTrigger = iota
    DATECREATED_RETENTIONTRIGGER
    DATEMODIFIED_RETENTIONTRIGGER
    DATEOFEVENT_RETENTIONTRIGGER
    UNKNOWNFUTUREVALUE_RETENTIONTRIGGER
)

func (i RetentionTrigger) String() string {
    return []string{"dateLabeled", "dateCreated", "dateModified", "dateOfEvent", "unknownFutureValue"}[i]
}
func ParseRetentionTrigger(v string) (any, error) {
    result := DATELABELED_RETENTIONTRIGGER
    switch v {
        case "dateLabeled":
            result = DATELABELED_RETENTIONTRIGGER
        case "dateCreated":
            result = DATECREATED_RETENTIONTRIGGER
        case "dateModified":
            result = DATEMODIFIED_RETENTIONTRIGGER
        case "dateOfEvent":
            result = DATEOFEVENT_RETENTIONTRIGGER
        case "unknownFutureValue":
            result = UNKNOWNFUTUREVALUE_RETENTIONTRIGGER
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeRetentionTrigger(values []RetentionTrigger) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i RetentionTrigger) isMultiValue() bool {
    return false
}
