// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
// Possible values for applicationGuardBlockFileTransfer
type ApplicationGuardBlockFileTransferType int

const (
    // Not Configured
    NOTCONFIGURED_APPLICATIONGUARDBLOCKFILETRANSFERTYPE ApplicationGuardBlockFileTransferType = iota
    // Block clipboard to transfer Image and Text file
    BLOCKIMAGEANDTEXTFILE_APPLICATIONGUARDBLOCKFILETRANSFERTYPE
    // Block clipboard to transfer Image file
    BLOCKIMAGEFILE_APPLICATIONGUARDBLOCKFILETRANSFERTYPE
    // Neither of text file or image file is blocked from transferring
    BLOCKNONE_APPLICATIONGUARDBLOCKFILETRANSFERTYPE
    // Block clipboard to transfer Text file
    BLOCKTEXTFILE_APPLICATIONGUARDBLOCKFILETRANSFERTYPE
)

func (i ApplicationGuardBlockFileTransferType) String() string {
    return []string{"notConfigured", "blockImageAndTextFile", "blockImageFile", "blockNone", "blockTextFile"}[i]
}
func ParseApplicationGuardBlockFileTransferType(v string) (any, error) {
    result := NOTCONFIGURED_APPLICATIONGUARDBLOCKFILETRANSFERTYPE
    switch v {
        case "notConfigured":
            result = NOTCONFIGURED_APPLICATIONGUARDBLOCKFILETRANSFERTYPE
        case "blockImageAndTextFile":
            result = BLOCKIMAGEANDTEXTFILE_APPLICATIONGUARDBLOCKFILETRANSFERTYPE
        case "blockImageFile":
            result = BLOCKIMAGEFILE_APPLICATIONGUARDBLOCKFILETRANSFERTYPE
        case "blockNone":
            result = BLOCKNONE_APPLICATIONGUARDBLOCKFILETRANSFERTYPE
        case "blockTextFile":
            result = BLOCKTEXTFILE_APPLICATIONGUARDBLOCKFILETRANSFERTYPE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeApplicationGuardBlockFileTransferType(values []ApplicationGuardBlockFileTransferType) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i ApplicationGuardBlockFileTransferType) isMultiValue() bool {
    return false
}
