// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
type AuthenticationMethodPlatform int

const (
    UNKNOWN_AUTHENTICATIONMETHODPLATFORM AuthenticationMethodPlatform = iota
    WINDOWS_AUTHENTICATIONMETHODPLATFORM
    MACOS_AUTHENTICATIONMETHODPLATFORM
    IOS_AUTHENTICATIONMETHODPLATFORM
    ANDROID_AUTHENTICATIONMETHODPLATFORM
    LINUX_AUTHENTICATIONMETHODPLATFORM
    UNKNOWNFUTUREVALUE_AUTHENTICATIONMETHODPLATFORM
)

func (i AuthenticationMethodPlatform) String() string {
    return []string{"unknown", "windows", "macOS", "iOS", "android", "linux", "unknownFutureValue"}[i]
}
func ParseAuthenticationMethodPlatform(v string) (any, error) {
    result := UNKNOWN_AUTHENTICATIONMETHODPLATFORM
    switch v {
        case "unknown":
            result = UNKNOWN_AUTHENTICATIONMETHODPLATFORM
        case "windows":
            result = WINDOWS_AUTHENTICATIONMETHODPLATFORM
        case "macOS":
            result = MACOS_AUTHENTICATIONMETHODPLATFORM
        case "iOS":
            result = IOS_AUTHENTICATIONMETHODPLATFORM
        case "android":
            result = ANDROID_AUTHENTICATIONMETHODPLATFORM
        case "linux":
            result = LINUX_AUTHENTICATIONMETHODPLATFORM
        case "unknownFutureValue":
            result = UNKNOWNFUTUREVALUE_AUTHENTICATIONMETHODPLATFORM
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeAuthenticationMethodPlatform(values []AuthenticationMethodPlatform) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i AuthenticationMethodPlatform) isMultiValue() bool {
    return false
}
