// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type ProcessContentMetadataBase struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // Represents the actual content, either as text (textContent) or binary data (binaryContent). Optional if metadata alone is sufficient for policy evaluation. Do not use for contentActivities.
    content ContentBaseable
    // An identifier used to group multiple related content entries (for example, different parts of the same file upload, messages in a conversation).
    correlationId *string
    // Required. Timestamp indicating when the original content was created (for example, file creation time, message sent time).
    createdDateTime *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
    // Required. A unique identifier for this specific content entry within the context of the calling application or enforcement plane (for example, message ID, file path/URL).
    identifier *string
    // Required. Indicates if the provided content has been truncated from its original form (for example, due to size limits).
    isTruncated *bool
    // The length of the original content in bytes.
    length *int64
    // Required. Timestamp indicating when the original content was last modified. For ephemeral content like messages, this might be the same as createdDateTime.
    modifiedDateTime *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
    // Required. A descriptive name for the content (for example, file name, web page title, 'Chat Message').
    name *string
    // The OdataType property
    odataType *string
    // A sequence number indicating the order in which content was generated or should be processed, required when correlationId is used.
    sequenceNumber *int64
}
// NewProcessContentMetadataBase instantiates a new ProcessContentMetadataBase and sets the default values.
func NewProcessContentMetadataBase()(*ProcessContentMetadataBase) {
    m := &ProcessContentMetadataBase{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateProcessContentMetadataBaseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateProcessContentMetadataBaseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    if parseNode != nil {
        mappingValueNode, err := parseNode.GetChildNode("@odata.type")
        if err != nil {
            return nil, err
        }
        if mappingValueNode != nil {
            mappingValue, err := mappingValueNode.GetStringValue()
            if err != nil {
                return nil, err
            }
            if mappingValue != nil {
                switch *mappingValue {
                    case "#microsoft.graph.processConversationMetadata":
                        return NewProcessConversationMetadata(), nil
                    case "#microsoft.graph.processFileMetadata":
                        return NewProcessFileMetadata(), nil
                }
            }
        }
    }
    return NewProcessContentMetadataBase(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *ProcessContentMetadataBase) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetContent gets the content property value. Represents the actual content, either as text (textContent) or binary data (binaryContent). Optional if metadata alone is sufficient for policy evaluation. Do not use for contentActivities.
// returns a ContentBaseable when successful
func (m *ProcessContentMetadataBase) GetContent()(ContentBaseable) {
    return m.content
}
// GetCorrelationId gets the correlationId property value. An identifier used to group multiple related content entries (for example, different parts of the same file upload, messages in a conversation).
// returns a *string when successful
func (m *ProcessContentMetadataBase) GetCorrelationId()(*string) {
    return m.correlationId
}
// GetCreatedDateTime gets the createdDateTime property value. Required. Timestamp indicating when the original content was created (for example, file creation time, message sent time).
// returns a *Time when successful
func (m *ProcessContentMetadataBase) GetCreatedDateTime()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.createdDateTime
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *ProcessContentMetadataBase) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["content"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateContentBaseFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetContent(val.(ContentBaseable))
        }
        return nil
    }
    res["correlationId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCorrelationId(val)
        }
        return nil
    }
    res["createdDateTime"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCreatedDateTime(val)
        }
        return nil
    }
    res["identifier"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetIdentifier(val)
        }
        return nil
    }
    res["isTruncated"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetIsTruncated(val)
        }
        return nil
    }
    res["length"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLength(val)
        }
        return nil
    }
    res["modifiedDateTime"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetModifiedDateTime(val)
        }
        return nil
    }
    res["name"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetName(val)
        }
        return nil
    }
    res["@odata.type"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetOdataType(val)
        }
        return nil
    }
    res["sequenceNumber"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSequenceNumber(val)
        }
        return nil
    }
    return res
}
// GetIdentifier gets the identifier property value. Required. A unique identifier for this specific content entry within the context of the calling application or enforcement plane (for example, message ID, file path/URL).
// returns a *string when successful
func (m *ProcessContentMetadataBase) GetIdentifier()(*string) {
    return m.identifier
}
// GetIsTruncated gets the isTruncated property value. Required. Indicates if the provided content has been truncated from its original form (for example, due to size limits).
// returns a *bool when successful
func (m *ProcessContentMetadataBase) GetIsTruncated()(*bool) {
    return m.isTruncated
}
// GetLength gets the length property value. The length of the original content in bytes.
// returns a *int64 when successful
func (m *ProcessContentMetadataBase) GetLength()(*int64) {
    return m.length
}
// GetModifiedDateTime gets the modifiedDateTime property value. Required. Timestamp indicating when the original content was last modified. For ephemeral content like messages, this might be the same as createdDateTime.
// returns a *Time when successful
func (m *ProcessContentMetadataBase) GetModifiedDateTime()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.modifiedDateTime
}
// GetName gets the name property value. Required. A descriptive name for the content (for example, file name, web page title, 'Chat Message').
// returns a *string when successful
func (m *ProcessContentMetadataBase) GetName()(*string) {
    return m.name
}
// GetOdataType gets the @odata.type property value. The OdataType property
// returns a *string when successful
func (m *ProcessContentMetadataBase) GetOdataType()(*string) {
    return m.odataType
}
// GetSequenceNumber gets the sequenceNumber property value. A sequence number indicating the order in which content was generated or should be processed, required when correlationId is used.
// returns a *int64 when successful
func (m *ProcessContentMetadataBase) GetSequenceNumber()(*int64) {
    return m.sequenceNumber
}
// Serialize serializes information the current object
func (m *ProcessContentMetadataBase) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("content", m.GetContent())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("correlationId", m.GetCorrelationId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteTimeValue("createdDateTime", m.GetCreatedDateTime())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("identifier", m.GetIdentifier())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("isTruncated", m.GetIsTruncated())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt64Value("length", m.GetLength())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteTimeValue("modifiedDateTime", m.GetModifiedDateTime())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("name", m.GetName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("@odata.type", m.GetOdataType())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt64Value("sequenceNumber", m.GetSequenceNumber())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *ProcessContentMetadataBase) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetContent sets the content property value. Represents the actual content, either as text (textContent) or binary data (binaryContent). Optional if metadata alone is sufficient for policy evaluation. Do not use for contentActivities.
func (m *ProcessContentMetadataBase) SetContent(value ContentBaseable)() {
    m.content = value
}
// SetCorrelationId sets the correlationId property value. An identifier used to group multiple related content entries (for example, different parts of the same file upload, messages in a conversation).
func (m *ProcessContentMetadataBase) SetCorrelationId(value *string)() {
    m.correlationId = value
}
// SetCreatedDateTime sets the createdDateTime property value. Required. Timestamp indicating when the original content was created (for example, file creation time, message sent time).
func (m *ProcessContentMetadataBase) SetCreatedDateTime(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.createdDateTime = value
}
// SetIdentifier sets the identifier property value. Required. A unique identifier for this specific content entry within the context of the calling application or enforcement plane (for example, message ID, file path/URL).
func (m *ProcessContentMetadataBase) SetIdentifier(value *string)() {
    m.identifier = value
}
// SetIsTruncated sets the isTruncated property value. Required. Indicates if the provided content has been truncated from its original form (for example, due to size limits).
func (m *ProcessContentMetadataBase) SetIsTruncated(value *bool)() {
    m.isTruncated = value
}
// SetLength sets the length property value. The length of the original content in bytes.
func (m *ProcessContentMetadataBase) SetLength(value *int64)() {
    m.length = value
}
// SetModifiedDateTime sets the modifiedDateTime property value. Required. Timestamp indicating when the original content was last modified. For ephemeral content like messages, this might be the same as createdDateTime.
func (m *ProcessContentMetadataBase) SetModifiedDateTime(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.modifiedDateTime = value
}
// SetName sets the name property value. Required. A descriptive name for the content (for example, file name, web page title, 'Chat Message').
func (m *ProcessContentMetadataBase) SetName(value *string)() {
    m.name = value
}
// SetOdataType sets the @odata.type property value. The OdataType property
func (m *ProcessContentMetadataBase) SetOdataType(value *string)() {
    m.odataType = value
}
// SetSequenceNumber sets the sequenceNumber property value. A sequence number indicating the order in which content was generated or should be processed, required when correlationId is used.
func (m *ProcessContentMetadataBase) SetSequenceNumber(value *int64)() {
    m.sequenceNumber = value
}
type ProcessContentMetadataBaseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetContent()(ContentBaseable)
    GetCorrelationId()(*string)
    GetCreatedDateTime()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetIdentifier()(*string)
    GetIsTruncated()(*bool)
    GetLength()(*int64)
    GetModifiedDateTime()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetName()(*string)
    GetOdataType()(*string)
    GetSequenceNumber()(*int64)
    SetContent(value ContentBaseable)()
    SetCorrelationId(value *string)()
    SetCreatedDateTime(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetIdentifier(value *string)()
    SetIsTruncated(value *bool)()
    SetLength(value *int64)()
    SetModifiedDateTime(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetName(value *string)()
    SetOdataType(value *string)()
    SetSequenceNumber(value *int64)()
}
