// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
// Specifies what level of safe search (filtering adult content) is required
type SafeSearchFilterType int

const (
    // User Defined, default value, no intent.
    USERDEFINED_SAFESEARCHFILTERTYPE SafeSearchFilterType = iota
    // Strict, highest filtering against adult content.
    STRICT_SAFESEARCHFILTERTYPE
    // Moderate filtering against adult content (valid search results will not be filtered).
    MODERATE_SAFESEARCHFILTERTYPE
)

func (i SafeSearchFilterType) String() string {
    return []string{"userDefined", "strict", "moderate"}[i]
}
func ParseSafeSearchFilterType(v string) (any, error) {
    result := USERDEFINED_SAFESEARCHFILTERTYPE
    switch v {
        case "userDefined":
            result = USERDEFINED_SAFESEARCHFILTERTYPE
        case "strict":
            result = STRICT_SAFESEARCHFILTERTYPE
        case "moderate":
            result = MODERATE_SAFESEARCHFILTERTYPE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeSafeSearchFilterType(values []SafeSearchFilterType) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i SafeSearchFilterType) isMultiValue() bool {
    return false
}
