// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
type Status int

const (
    ACTIVE_STATUS Status = iota
    UPDATED_STATUS
    DELETED_STATUS
    IGNORED_STATUS
    UNKNOWNFUTUREVALUE_STATUS
)

func (i Status) String() string {
    return []string{"active", "updated", "deleted", "ignored", "unknownFutureValue"}[i]
}
func ParseStatus(v string) (any, error) {
    result := ACTIVE_STATUS
    switch v {
        case "active":
            result = ACTIVE_STATUS
        case "updated":
            result = UPDATED_STATUS
        case "deleted":
            result = DELETED_STATUS
        case "ignored":
            result = IGNORED_STATUS
        case "unknownFutureValue":
            result = UNKNOWNFUTUREVALUE_STATUS
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeStatus(values []Status) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i Status) isMultiValue() bool {
    return false
}
