// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
type ThreatCategory int

const (
    UNDEFINED_THREATCATEGORY ThreatCategory = iota
    SPAM_THREATCATEGORY
    PHISHING_THREATCATEGORY
    MALWARE_THREATCATEGORY
    UNKNOWNFUTUREVALUE_THREATCATEGORY
)

func (i ThreatCategory) String() string {
    return []string{"undefined", "spam", "phishing", "malware", "unknownFutureValue"}[i]
}
func ParseThreatCategory(v string) (any, error) {
    result := UNDEFINED_THREATCATEGORY
    switch v {
        case "undefined":
            result = UNDEFINED_THREATCATEGORY
        case "spam":
            result = SPAM_THREATCATEGORY
        case "phishing":
            result = PHISHING_THREATCATEGORY
        case "malware":
            result = MALWARE_THREATCATEGORY
        case "unknownFutureValue":
            result = UNKNOWNFUTUREVALUE_THREATCATEGORY
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeThreatCategory(values []ThreatCategory) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i ThreatCategory) isMultiValue() bool {
    return false
}
