// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
type TitleAreaTextAlignmentType int

const (
    LEFT_TITLEAREATEXTALIGNMENTTYPE TitleAreaTextAlignmentType = iota
    CENTER_TITLEAREATEXTALIGNMENTTYPE
    UNKNOWNFUTUREVALUE_TITLEAREATEXTALIGNMENTTYPE
)

func (i TitleAreaTextAlignmentType) String() string {
    return []string{"left", "center", "unknownFutureValue"}[i]
}
func ParseTitleAreaTextAlignmentType(v string) (any, error) {
    result := LEFT_TITLEAREATEXTALIGNMENTTYPE
    switch v {
        case "left":
            result = LEFT_TITLEAREATEXTALIGNMENTTYPE
        case "center":
            result = CENTER_TITLEAREATEXTALIGNMENTTYPE
        case "unknownFutureValue":
            result = UNKNOWNFUTUREVALUE_TITLEAREATEXTALIGNMENTTYPE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeTitleAreaTextAlignmentType(values []TitleAreaTextAlignmentType) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i TitleAreaTextAlignmentType) isMultiValue() bool {
    return false
}
