// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
type UserExperienceAnalyticsHealthState int

const (
    // Indicates that the health state is unknown.
    UNKNOWN_USEREXPERIENCEANALYTICSHEALTHSTATE UserExperienceAnalyticsHealthState = iota
    // Indicates that the health state is insufficient data.
    INSUFFICIENTDATA_USEREXPERIENCEANALYTICSHEALTHSTATE
    // Indicates that the health state needs attention.
    NEEDSATTENTION_USEREXPERIENCEANALYTICSHEALTHSTATE
    // Indicates that the health state is meeting goals.
    MEETINGGOALS_USEREXPERIENCEANALYTICSHEALTHSTATE
    // Evolvable enumeration sentinel value. Do not use.
    UNKNOWNFUTUREVALUE_USEREXPERIENCEANALYTICSHEALTHSTATE
)

func (i UserExperienceAnalyticsHealthState) String() string {
    return []string{"unknown", "insufficientData", "needsAttention", "meetingGoals", "unknownFutureValue"}[i]
}
func ParseUserExperienceAnalyticsHealthState(v string) (any, error) {
    result := UNKNOWN_USEREXPERIENCEANALYTICSHEALTHSTATE
    switch v {
        case "unknown":
            result = UNKNOWN_USEREXPERIENCEANALYTICSHEALTHSTATE
        case "insufficientData":
            result = INSUFFICIENTDATA_USEREXPERIENCEANALYTICSHEALTHSTATE
        case "needsAttention":
            result = NEEDSATTENTION_USEREXPERIENCEANALYTICSHEALTHSTATE
        case "meetingGoals":
            result = MEETINGGOALS_USEREXPERIENCEANALYTICSHEALTHSTATE
        case "unknownFutureValue":
            result = UNKNOWNFUTUREVALUE_USEREXPERIENCEANALYTICSHEALTHSTATE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeUserExperienceAnalyticsHealthState(values []UserExperienceAnalyticsHealthState) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i UserExperienceAnalyticsHealthState) isMultiValue() bool {
    return false
}
