name: Publish-CloudFormation

on:
  push:
    branches:
      - main
      - "[0-9]+.[0-9]+"
    paths:
      - deploy/cloudformation/*.yml
      - scripts/publish_cft.sh
      - .github/workflows/publish-cloudformation.yml

jobs:
  publish_cloudformation:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Upload to S3 if elastic-agent CloudFormation template has changed
        run: ./scripts/publish_ft.sh
